title = "ci-service"

[app]
version="v0"
language="go"
name = "ci-service"
description = "build , test , push your code"
githubURL = "github.com/miladhzzz/milx-cloud-init/ci-service"

[app.services]
ports = ["", ""] # you can add your published ports here

[app.build]
build = "yes" # if set to yes build-server will build an image of docker file present and push it to private registry
imageTag = "ci-service:test1"
repositories = ["persys","azure-ACR"]

[app.test]
tests = "/tests"

[app.deploy]
deploy = "yes"
namespace = "test" # etc / dev / production / CICD
cloud = ["persys", "azure"]
replica= "3"
checkpoint = "tests"

[app.dependencis]
services = ["kafka", "mongodb"]
volumes = ""

[app.config]
file = "config.toml"