title = "persys-cicd"

[app.metadata]
description = "this is some microservice...."
version = "v0"
languages = "go , rust , nextjs"
owner = "https://githuh.com/miladhzzzz"
repo = "https://github.com/miladhzzzz/persys-cicd"

[app.build]
exclude = ""
dockerfile = "/{$WORKDIR}/Dockerfile"
kubernetes = "/{$WORKDIR}/Dockerfile"

[app.deploy]
namespace = "test"
replica = "1"

[app.tests]
tests = "/{$WORKDIR}/tests"

[app.tests.after]
namespace = "qa-1"
replica = 1

[app.dependencies]
depeondsOn = ["mongodb", "kafka"]