apiVersion : apps/v1
kind: Deployment
metadata:
  name: events-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-manager
  template:
    metadata:
      labels:
        app: events-manager
    spec:
      containers:
        - name: events-manager
          image: fingreg.azurecr.io/events-manager
          ports:
            - containerPort: 8662