[app]
httpAddr = ":8552"

storage = "Persistent Volume"

[app.metadata]
name = "blob-service"
description = "a very simple http based in-cluster artifact storage"

[log]
format = "json"
level = "info"

[telemetry]
addr = "signoz-otel-collector.persys-dev.svc.cluster.local:4317"