apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-manager
spec:
  selector:
    matchLabels:
      app: events-manager
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: events-manager
    spec:
      containers:
      - name: events-manager
        image: 192.168.13.131:5000/milx-kube-api:v0
        ports:
        - containerPort: 5000
