name: Docker Image CI

on:
  push:
    paths:
      - 'cluster-provider/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file cluster-provider/Dockerfile --tag cluster-provider:$(date +%s)