name: Docker Image CI

on:
  push:
    paths:
      - 'fabric-service/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file fabric-service/Dockerfile --tag fabric-service:$(date +%s)