name: Docker Image CI

on:
  push:
    paths:
      - 'api-gateway/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file api-gateway/Dockerfile --tag api-gateway:$(date +%s)
