name: Docker Image CI

on:
  push:
    paths:
      - 'blob-service/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file blob-service/Dockerfile --tag blob-service:$(date +%s)