name: Docker Image CI

on:
  push:
    paths:
      - 'cloud-mgmt/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file cloud-mgmt/Dockerfile --tag cloud-mgmt:$(date +%s)