name: Docker Image CI

on:
  push:
    paths:
      - 'monitoring-service/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file monitoring-service/Dockerfile --tag monitoring-service:$(date +%s)